before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: N+hg+tXeAC7wT1n/2NDw+wQF5W81IJ30be0D87mEuCXt7u/cx5UbfA132airbnX77psP7semQfxN2KPOO4EgWcITANY4muAkXU+xoN85CbdsZOsYvX0ShUScOKgP4ouCSOuANdY2nkB563k0BmJD5jCd558r5J/AKsWq/er8riRijQZThnmm4V2VxN4vZfowbbGpJveByOBUqcFdc90WlNUnYclZeuuaKlFx7+xm/POgDcSIBqhWflPjA0JwGfDnlqGiIz+3opNc9C+/F9b2Up2494x7Ofh1T5KSCbetL3+1Jdi6dBZVKufQoG8B0o9Iw8enw6ykOAUDFw1r6B8XFvyb0zo9bo+DE9EF/sJqzH2HDDOp2RT8q2JqdXayQ1zgLxdf3oiD/mDXplyPR1OBZHC8WwqenPGH/3rQXKlWZzjXd9VHUNK8S45sQdTxKpfo8lpVUw/kvnnAmapeg469oZnQgTpVICM0IC8s7CqeCbmtHWdcoLHX6wF/WUmdXLK+zzOEltHAh8+8bi58gd+Il4dNyPmxioHTUH9fLb5Avqm04204405BO/zHeC1G3q01K3LkREEBYktZwAbSAvHWnSRABmlSF+Br5voVWt2uA4DV5pgDFjsxLnx18i1AinFZIQ2qm10UBd1RAJPRLi7m3J4cHSdor26c2NhntJnu48I= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
